<?xml version="1.0" encoding="utf-8"?><Database Name="DauGia" Class="DataEntityDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=NGUYENDINHLUYEN\SQLEXPRESS;Initial Catalog=DauGia;User ID=vbay" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DauGiaConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.aspnet_Applications" Member="aspnet_Applications">
    <Type Name="aspnet_Application">
      <Column Name="ApplicationName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="LoweredApplicationName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Association Name="aspnet_Application_aspnet_Membership" Member="aspnet_Memberships" ThisKey="ApplicationId" OtherKey="ApplicationId" Type="aspnet_Membership" />
      <Association Name="aspnet_Application_aspnet_Path" Member="aspnet_Paths" ThisKey="ApplicationId" OtherKey="ApplicationId" Type="aspnet_Path" />
      <Association Name="aspnet_Application_aspnet_Role" Member="aspnet_Roles" ThisKey="ApplicationId" OtherKey="ApplicationId" Type="aspnet_Role" />
      <Association Name="aspnet_Application_aspnet_User" Member="aspnet_Users" ThisKey="ApplicationId" OtherKey="ApplicationId" Type="aspnet_User" />
    </Type>
  </Table>
  <Table Name="dbo.TinhTrangSanPham" Member="TinhTrangSanPhams">
    <Type Name="TinhTrangSanPham">
      <Column Name="MaTinhTrangSanPham" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenTinhTrangSanPham" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="TinhTrangSanPham_SanPham" Member="SanPhams" ThisKey="MaTinhTrangSanPham" OtherKey="MaTinhTrangSanPham" Type="SanPham" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Membership" Member="aspnet_Memberships">
    <Type Name="aspnet_Membership">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordFormat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PasswordSalt" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="MobilePIN" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="LoweredEmail" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="PasswordQuestion" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="PasswordAnswer" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="IsApproved" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsLockedOut" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastLoginDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastPasswordChangedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastLockoutDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAttemptCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAttemptWindowStart" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAnswerAttemptCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAnswerAttemptWindowStart" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Comment" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="aspnet_Application_aspnet_Membership" Member="aspnet_Application" ThisKey="ApplicationId" OtherKey="ApplicationId" Type="aspnet_Application" IsForeignKey="true" />
      <Association Name="aspnet_User_aspnet_Membership" Member="aspnet_User" ThisKey="UserId" OtherKey="UserId" Type="aspnet_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Paths" Member="aspnet_Paths">
    <Type Name="aspnet_Path">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="PathId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Path" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="LoweredPath" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Association Name="aspnet_Path_aspnet_PersonalizationAllUser" Member="aspnet_PersonalizationAllUser" ThisKey="PathId" OtherKey="PathId" Type="aspnet_PersonalizationAllUser" Cardinality="One" />
      <Association Name="aspnet_Path_aspnet_PersonalizationPerUser" Member="aspnet_PersonalizationPerUsers" ThisKey="PathId" OtherKey="PathId" Type="aspnet_PersonalizationPerUser" />
      <Association Name="aspnet_Application_aspnet_Path" Member="aspnet_Application" ThisKey="ApplicationId" OtherKey="ApplicationId" Type="aspnet_Application" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_PersonalizationAllUsers" Member="aspnet_PersonalizationAllUsers">
    <Type Name="aspnet_PersonalizationAllUser">
      <Column Name="PathId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PageSettings" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="LastUpdatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="aspnet_Path_aspnet_PersonalizationAllUser" Member="aspnet_Path" ThisKey="PathId" OtherKey="PathId" Type="aspnet_Path" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_PersonalizationPerUser" Member="aspnet_PersonalizationPerUsers">
    <Type Name="aspnet_PersonalizationPerUser">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PathId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="PageSettings" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="LastUpdatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="aspnet_Path_aspnet_PersonalizationPerUser" Member="aspnet_Path" ThisKey="PathId" OtherKey="PathId" Type="aspnet_Path" IsForeignKey="true" />
      <Association Name="aspnet_User_aspnet_PersonalizationPerUser" Member="aspnet_User" ThisKey="UserId" OtherKey="UserId" Type="aspnet_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Profile" Member="aspnet_Profiles">
    <Type Name="aspnet_Profile">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PropertyNames" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="PropertyValuesString" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="PropertyValuesBinary" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="LastUpdatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="aspnet_User_aspnet_Profile" Member="aspnet_User" ThisKey="UserId" OtherKey="UserId" Type="aspnet_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Roles" Member="aspnet_Roles">
    <Type Name="aspnet_Role">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="LoweredRoleName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Association Name="aspnet_Role_aspnet_UsersInRole" Member="aspnet_UsersInRoles" ThisKey="RoleId" OtherKey="RoleId" Type="aspnet_UsersInRole" />
      <Association Name="aspnet_Application_aspnet_Role" Member="aspnet_Application" ThisKey="ApplicationId" OtherKey="ApplicationId" Type="aspnet_Application" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_SchemaVersions" Member="aspnet_SchemaVersions">
    <Type Name="aspnet_SchemaVersion">
      <Column Name="Feature" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CompatibleSchemaVersion" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IsCurrentVersion" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Users" Member="aspnet_Users">
    <Type Name="aspnet_User">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="LoweredUserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="MobileAlias" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="IsAnonymous" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastActivityDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MaThongTinTaiKhoan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaThongTinDauGia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="aspnet_User_aspnet_Membership" Member="aspnet_Membership" ThisKey="UserId" OtherKey="UserId" Type="aspnet_Membership" Cardinality="One" />
      <Association Name="aspnet_User_aspnet_PersonalizationPerUser" Member="aspnet_PersonalizationPerUsers" ThisKey="UserId" OtherKey="UserId" Type="aspnet_PersonalizationPerUser" />
      <Association Name="aspnet_User_aspnet_Profile" Member="aspnet_Profile" ThisKey="UserId" OtherKey="UserId" Type="aspnet_Profile" Cardinality="One" />
      <Association Name="aspnet_User_aspnet_UsersInRole" Member="aspnet_UsersInRoles" ThisKey="UserId" OtherKey="UserId" Type="aspnet_UsersInRole" />
      <Association Name="aspnet_User_ChiTietDauGia" Member="ChiTietDauGias" ThisKey="UserId" OtherKey="MaTaiKhoan" Type="ChiTietDauGia" />
      <Association Name="aspnet_User_Comment" Member="Comments" ThisKey="UserId" OtherKey="MaTaiKhoan" Type="Comment" />
      <Association Name="aspnet_User_SanPham" Member="SanPhams" ThisKey="UserId" OtherKey="MaTaiKhoan" Type="SanPham" />
      <Association Name="aspnet_Application_aspnet_User" Member="aspnet_Application" ThisKey="ApplicationId" OtherKey="ApplicationId" Type="aspnet_Application" IsForeignKey="true" />
      <Association Name="ThongTinDauGia_aspnet_User" Member="ThongTinDauGia" ThisKey="MaThongTinDauGia" OtherKey="MaThongTinDauGia" Type="ThongTinDauGia" IsForeignKey="true" />
      <Association Name="ThongTinTaiKhoan_aspnet_User" Member="ThongTinTaiKhoan" ThisKey="MaThongTinTaiKhoan" OtherKey="MaThongTinTaiKhoan" Type="ThongTinTaiKhoan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_UsersInRoles" Member="aspnet_UsersInRoles">
    <Type Name="aspnet_UsersInRole">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="aspnet_Role_aspnet_UsersInRole" Member="aspnet_Role" ThisKey="RoleId" OtherKey="RoleId" Type="aspnet_Role" IsForeignKey="true" />
      <Association Name="aspnet_User_aspnet_UsersInRole" Member="aspnet_User" ThisKey="UserId" OtherKey="UserId" Type="aspnet_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_WebEvent_Events" Member="aspnet_WebEvent_Events">
    <Type Name="aspnet_WebEvent_Event">
      <Column Name="EventId" Type="System.String" DbType="Char(32) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EventTimeUtc" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EventTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EventType" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="EventSequence" Type="System.Decimal" DbType="Decimal(19,0) NOT NULL" CanBeNull="false" />
      <Column Name="EventOccurrence" Type="System.Decimal" DbType="Decimal(19,0) NOT NULL" CanBeNull="false" />
      <Column Name="EventCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EventDetailCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="ApplicationPath" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="ApplicationVirtualPath" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="MachineName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="RequestUrl" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="ExceptionType" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Details" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietDauGia" Member="ChiTietDauGias">
    <Type Name="ChiTietDauGia">
      <Column Name="MaChiTietDauGia" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaTaiKhoan" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="MaSanPham" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GiaGiaoDich" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThoiGianGiaoDich" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="ChiTietDauGia_DauGiaThanhCong" Member="DauGiaThanhCongs" ThisKey="MaChiTietDauGia" OtherKey="MaChiTietGiaoDich" Type="DauGiaThanhCong" />
      <Association Name="aspnet_User_ChiTietDauGia" Member="aspnet_User" ThisKey="MaTaiKhoan" OtherKey="UserId" Type="aspnet_User" IsForeignKey="true" />
      <Association Name="SanPham_ChiTietDauGia" Member="SanPham" ThisKey="MaSanPham" OtherKey="MaSanPham" Type="SanPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietPhanQuyen" Member="ChiTietPhanQuyens">
    <Type Name="ChiTietPhanQuyen">
      <Column Name="MaChiTietPhanQuyen" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaLoaiTaiKhoan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaPhanQuyen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="LoaiTaiKhoan_ChiTietPhanQuyen" Member="LoaiTaiKhoan" ThisKey="MaLoaiTaiKhoan" OtherKey="MaLoaiTaiKhoan" Type="LoaiTaiKhoan" IsForeignKey="true" />
      <Association Name="PhanQuyen_ChiTietPhanQuyen" Member="PhanQuyen" ThisKey="MaPhanQuyen" OtherKey="MaPhanQuyen" Type="PhanQuyen" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Comment" Member="Comments">
    <Type Name="Comment">
      <Column Name="MaComment" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaTaiKhoan" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="MaSanPham" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NoiDungComment" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="NgayComment" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="aspnet_User_Comment" Member="aspnet_User" ThisKey="MaTaiKhoan" OtherKey="UserId" Type="aspnet_User" IsForeignKey="true" />
      <Association Name="SanPham_Comment" Member="SanPham" ThisKey="MaSanPham" OtherKey="MaSanPham" Type="SanPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DauGiaThanhCong" Member="DauGiaThanhCongs">
    <Type Name="DauGiaThanhCong">
      <Column Name="MaDauGiaThanhCong" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaChiTietGiaoDich" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GiaKhopLenh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ChiTietDauGia_DauGiaThanhCong" Member="ChiTietDauGia" ThisKey="MaChiTietGiaoDich" OtherKey="MaChiTietDauGia" Type="ChiTietDauGia" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GiaoDien" Member="GiaoDiens">
    <Type Name="GiaoDien">
      <Column Name="MaGiaoDien" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenTheme" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.GioiTinh" Member="GioiTinhs">
    <Type Name="GioiTinh">
      <Column Name="MaGioiTinh" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenGioiTinh" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Association Name="GioiTinh_ThongTinTaiKhoan" Member="ThongTinTaiKhoans" ThisKey="MaGioiTinh" OtherKey="MaGioiTinh" Type="ThongTinTaiKhoan" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiMultimedia" Member="LoaiMultimedias">
    <Type Name="LoaiMultimedia">
      <Column Name="MaLoaiMT" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenLoaiMT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="LoaiMultimedia_Multimedia" Member="Multimedias" ThisKey="MaLoaiMT" OtherKey="MaLoaiMT" Type="Multimedia" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiSanPham" Member="LoaiSanPhams">
    <Type Name="LoaiSanPham">
      <Column Name="MaLoaiSanPham" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenLoaiSanPham" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="LoaiSanPham_SanPham" Member="SanPhams" ThisKey="MaLoaiSanPham" OtherKey="MaLoaiSanPham" Type="SanPham" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiTaiKhoan" Member="LoaiTaiKhoans">
    <Type Name="LoaiTaiKhoan">
      <Column Name="MaLoaiTaiKhoan" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenLoaiTaiKhoan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="LoaiTaiKhoan_ChiTietPhanQuyen" Member="ChiTietPhanQuyens" ThisKey="MaLoaiTaiKhoan" OtherKey="MaLoaiTaiKhoan" Type="ChiTietPhanQuyen" />
    </Type>
  </Table>
  <Table Name="dbo.Multimedia" Member="Multimedias">
    <Type Name="Multimedia">
      <Column Name="MaMT" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenMT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaLoaiMT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DungLuong" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="KichThuoc" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="LinkURL" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Multimedia_SanPham" Member="SanPhams" ThisKey="MaMT" OtherKey="MaHinhMoTa" Type="SanPham" />
      <Association Name="Multimedia_SanPham_Multimedia" Member="SanPham_Multimedias" ThisKey="MaMT" OtherKey="MaMT" Type="SanPham_Multimedia" />
      <Association Name="LoaiMultimedia_Multimedia" Member="LoaiMultimedia" ThisKey="MaLoaiMT" OtherKey="MaLoaiMT" Type="LoaiMultimedia" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhanQuyen" Member="PhanQuyens">
    <Type Name="PhanQuyen">
      <Column Name="MaPhanQuyen" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenQuyen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="PhanQuyen_ChiTietPhanQuyen" Member="ChiTietPhanQuyens" ThisKey="MaPhanQuyen" OtherKey="MaPhanQuyen" Type="ChiTietPhanQuyen" />
    </Type>
  </Table>
  <Table Name="dbo.SanPham" Member="SanPhams">
    <Type Name="SanPham">
      <Column Name="MaSanPham" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaTaiKhoan" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="MaLoaiSanPham" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaTinhTrangSanPham" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaHinhMoTa" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenSanPham" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GiaKhoiDiem" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="GiaHienTai" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="NgayDang" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayHetHan" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MoTaSanPham" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="SanPham_ChiTietDauGia" Member="ChiTietDauGias" ThisKey="MaSanPham" OtherKey="MaSanPham" Type="ChiTietDauGia" />
      <Association Name="SanPham_Comment" Member="Comments" ThisKey="MaSanPham" OtherKey="MaSanPham" Type="Comment" />
      <Association Name="SanPham_SanPham_Multimedia" Member="SanPham_Multimedias" ThisKey="MaSanPham" OtherKey="MaSanPham" Type="SanPham_Multimedia" />
      <Association Name="aspnet_User_SanPham" Member="aspnet_User" ThisKey="MaTaiKhoan" OtherKey="UserId" Type="aspnet_User" IsForeignKey="true" />
      <Association Name="LoaiSanPham_SanPham" Member="LoaiSanPham" ThisKey="MaLoaiSanPham" OtherKey="MaLoaiSanPham" Type="LoaiSanPham" IsForeignKey="true" />
      <Association Name="Multimedia_SanPham" Member="Multimedia" ThisKey="MaHinhMoTa" OtherKey="MaMT" Type="Multimedia" IsForeignKey="true" />
      <Association Name="TinhTrangSanPham_SanPham" Member="TinhTrangSanPham" ThisKey="MaTinhTrangSanPham" OtherKey="MaTinhTrangSanPham" Type="TinhTrangSanPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SanPham_Multimedia" Member="SanPham_Multimedias">
    <Type Name="SanPham_Multimedia">
      <Column Name="MaChiTietMT" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaSanPham" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaMT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SanPham_SanPham_Multimedia" Member="SanPham" ThisKey="MaSanPham" OtherKey="MaSanPham" Type="SanPham" IsForeignKey="true" />
      <Association Name="Multimedia_SanPham_Multimedia" Member="Multimedia" ThisKey="MaMT" OtherKey="MaMT" Type="Multimedia" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TaiKhoan" Member="TaiKhoans">
    <Type Name="TaiKhoan">
      <Column Name="TenTaiKhoan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MaLoaiTaiKhoan" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Avatar" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiemTinCayBan" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DiemTinCayMua" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="BiXoa" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="MaTaiKhoan" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.THAMSO" Member="THAMSOs">
    <Type Name="THAMSO">
      <Column Name="IDThamSo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenThamSo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GiaTri" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ThongTinDauGia" Member="ThongTinDauGias">
    <Type Name="ThongTinDauGia">
      <Column Name="MaThongTinDauGia" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DiemTinCayMua" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DiemTinCayBan" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="ThongTinDauGia_aspnet_User" Member="aspnet_Users" ThisKey="MaThongTinDauGia" OtherKey="MaThongTinDauGia" Type="aspnet_User" />
    </Type>
  </Table>
  <Table Name="dbo.ThongTinTaiKhoan" Member="ThongTinTaiKhoans">
    <Type Name="ThongTinTaiKhoan">
      <Column Name="MaThongTinTaiKhoan" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaGioiTinh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoDienThoai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaTheTinDung" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Avatar" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="ThongTinTaiKhoan_aspnet_User" Member="aspnet_Users" ThisKey="MaThongTinTaiKhoan" OtherKey="MaThongTinTaiKhoan" Type="aspnet_User" />
      <Association Name="GioiTinh_ThongTinTaiKhoan" Member="GioiTinh" ThisKey="MaGioiTinh" OtherKey="MaGioiTinh" Type="GioiTinh" IsForeignKey="true" />
    </Type>
  </Table>
</Database>