//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace vBay.WUC {
    
    
    public partial class WUCChiTietSanPham {
        
        /// <summary>
        /// WUCThongTinSanPhamVaShop1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::vBay.WUC.WUCThongTinSanPhamVaShop WUCThongTinSanPhamVaShop1;
        
        /// <summary>
        /// WUCBinhLuanSanPham1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::vBay.WUC.WUCBinhLuanSanPham WUCBinhLuanSanPham1;
    }
}
