<?xml version="1.0" encoding="utf-8"?><Database Name="DauGia" Class="MyDLinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=YAMA-PC;Initial Catalog=DauGia;User ID=vbay" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DauGiaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ChiTietDauGia" Member="ChiTietDauGias">
    <Type Name="ChiTietDauGia">
      <Column Name="MaChiTietDauGia" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaTaiKhoan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GiaGiaoDich" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThoiGianGiaoDich" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaSanPham" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ChiTietDauGia_DauGiaThanhCong" Member="DauGiaThanhCongs" ThisKey="MaChiTietDauGia" OtherKey="MaChiTietGiaoDich" Type="DauGiaThanhCong" />
      <Association Name="SanPham_ChiTietDauGia" Member="SanPham" ThisKey="MaSanPham" OtherKey="MaSanPham" Type="SanPham" IsForeignKey="true" />
      <Association Name="TaiKhoan_ChiTietDauGia" Member="TaiKhoan" ThisKey="MaTaiKhoan" OtherKey="MaTaiKhoan" Type="TaiKhoan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ThongTinTaiKhoan" Member="ThongTinTaiKhoans">
    <Type Name="ThongTinTaiKhoan">
      <Column Name="MaTaiKhoan" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NoiSinh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoDienThoai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaTheTinhDung" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="ThongTinTaiKhoan_TaiKhoan" Member="TaiKhoan" ThisKey="MaTaiKhoan" OtherKey="MaTaiKhoan" Type="TaiKhoan" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietPhanQuyen" Member="ChiTietPhanQuyens">
    <Type Name="ChiTietPhanQuyen">
      <Column Name="MaChiTietPhanQuyen" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaLoaiTaiKhoan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaPhanQuyen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="LoaiTaiKhoan_ChiTietPhanQuyen" Member="LoaiTaiKhoan" ThisKey="MaLoaiTaiKhoan" OtherKey="MaLoaiTaiKhoan" Type="LoaiTaiKhoan" IsForeignKey="true" />
      <Association Name="PhanQuyen_ChiTietPhanQuyen" Member="PhanQuyen" ThisKey="MaPhanQuyen" OtherKey="MaPhanQuyen" Type="PhanQuyen" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Comment" Member="Comments">
    <Type Name="Comment">
      <Column Name="MaComment" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NoiDungComment" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="NgayComment" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MaTaiKhoan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaSanPham" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="SanPham_Comment" Member="SanPham" ThisKey="MaSanPham" OtherKey="MaSanPham" Type="SanPham" IsForeignKey="true" />
      <Association Name="TaiKhoan_Comment" Member="TaiKhoan" ThisKey="MaTaiKhoan" OtherKey="MaTaiKhoan" Type="TaiKhoan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DauGiaThanhCong" Member="DauGiaThanhCongs">
    <Type Name="DauGiaThanhCong">
      <Column Name="MaDauGiaThanhCong" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaTaiKhoan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GiaKhopLenh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaChiTietGiaoDich" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Association Name="ChiTietDauGia_DauGiaThanhCong" Member="ChiTietDauGia" ThisKey="MaChiTietGiaoDich" OtherKey="MaChiTietDauGia" Type="ChiTietDauGia" IsForeignKey="true" />
      <Association Name="TaiKhoan_DauGiaThanhCong" Member="TaiKhoan" ThisKey="MaTaiKhoan" OtherKey="MaTaiKhoan" Type="TaiKhoan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GiaoDien" Member="GiaoDiens">
    <Type Name="GiaoDien">
      <Column Name="MaGiaoDien" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenTheme" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiMultimedia" Member="LoaiMultimedias">
    <Type Name="LoaiMultimedia">
      <Column Name="MaLoaiMT" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenLoaiMT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="LoaiMultimedia_Multimedia" Member="Multimedias" ThisKey="MaLoaiMT" OtherKey="MaLoaiMT" Type="Multimedia" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiSanPham" Member="LoaiSanPhams">
    <Type Name="LoaiSanPham">
      <Column Name="MaLoaiSanPham" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenLoaiSanPham" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="LoaiSanPham_SanPham" Member="SanPhams" ThisKey="MaLoaiSanPham" OtherKey="MaLoaiSanPham" Type="SanPham" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiTaiKhoan" Member="LoaiTaiKhoans">
    <Type Name="LoaiTaiKhoan">
      <Column Name="MaLoaiTaiKhoan" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenLoaiTaiKhoan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="LoaiTaiKhoan_ChiTietPhanQuyen" Member="ChiTietPhanQuyens" ThisKey="MaLoaiTaiKhoan" OtherKey="MaLoaiTaiKhoan" Type="ChiTietPhanQuyen" />
      <Association Name="LoaiTaiKhoan_TaiKhoan" Member="TaiKhoans" ThisKey="MaLoaiTaiKhoan" OtherKey="MaLoaiTaiKhoan" Type="TaiKhoan" />
    </Type>
  </Table>
  <Table Name="dbo.Multimedia" Member="Multimedias">
    <Type Name="Multimedia">
      <Column Name="MaMT" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenMT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaLoaiMT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DungLuong" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="KichThuoc" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="LinkURL" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Multimedia_SanPham" Member="SanPhams" ThisKey="MaMT" OtherKey="MaHinhMoTa" Type="SanPham" />
      <Association Name="Multimedia_SanPham_Multimedia" Member="SanPham_Multimedias" ThisKey="MaMT" OtherKey="MaMT" Type="SanPham_Multimedia" />
      <Association Name="LoaiMultimedia_Multimedia" Member="LoaiMultimedia" ThisKey="MaLoaiMT" OtherKey="MaLoaiMT" Type="LoaiMultimedia" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhanQuyen" Member="PhanQuyens">
    <Type Name="PhanQuyen">
      <Column Name="MaPhanQuyen" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenQuyen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="PhanQuyen_ChiTietPhanQuyen" Member="ChiTietPhanQuyens" ThisKey="MaPhanQuyen" OtherKey="MaPhanQuyen" Type="ChiTietPhanQuyen" />
    </Type>
  </Table>
  <Table Name="dbo.SanPham" Member="SanPhams">
    <Type Name="SanPham">
      <Column Name="MaSanPham" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenSanPham" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaLoaiSanPham" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaTaiKhoan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GiaKhoiDiem" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="GiaHienTai" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="NgayDang" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayHetHan" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MaTinhTrangSanPham" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MoTaSanPham" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaHinhMoTa" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SanPham_ChiTietDauGia" Member="ChiTietDauGias" ThisKey="MaSanPham" OtherKey="MaSanPham" Type="ChiTietDauGia" />
      <Association Name="SanPham_Comment" Member="Comments" ThisKey="MaSanPham" OtherKey="MaSanPham" Type="Comment" />
      <Association Name="SanPham_SanPham_Multimedia" Member="SanPham_Multimedias" ThisKey="MaSanPham" OtherKey="MaSanPham" Type="SanPham_Multimedia" />
      <Association Name="LoaiSanPham_SanPham" Member="LoaiSanPham" ThisKey="MaLoaiSanPham" OtherKey="MaLoaiSanPham" Type="LoaiSanPham" IsForeignKey="true" />
      <Association Name="Multimedia_SanPham" Member="Multimedia" ThisKey="MaHinhMoTa" OtherKey="MaMT" Type="Multimedia" IsForeignKey="true" />
      <Association Name="TaiKhoan_SanPham" Member="TaiKhoan" ThisKey="MaTaiKhoan" OtherKey="MaTaiKhoan" Type="TaiKhoan" IsForeignKey="true" />
      <Association Name="TinhTrangSanPham_SanPham" Member="TinhTrangSanPham" ThisKey="MaTinhTrangSanPham" OtherKey="MaTinhTrangSanPham" Type="TinhTrangSanPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SanPham_Multimedia" Member="SanPham_Multimedias">
    <Type Name="SanPham_Multimedia">
      <Column Name="MaChiTietMT" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaSanPham" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaMT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SanPham_SanPham_Multimedia" Member="SanPham" ThisKey="MaSanPham" OtherKey="MaSanPham" Type="SanPham" IsForeignKey="true" />
      <Association Name="Multimedia_SanPham_Multimedia" Member="Multimedia" ThisKey="MaMT" OtherKey="MaMT" Type="Multimedia" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TaiKhoan" Member="TaiKhoans">
    <Type Name="TaiKhoan">
      <Column Name="MaTaiKhoan" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenTaiKhoan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MaLoaiTaiKhoan" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Avatar" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiemTinCayBan" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DiemTinCayMua" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="BiXoa" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TaiKhoan_ChiTietDauGia" Member="ChiTietDauGias" ThisKey="MaTaiKhoan" OtherKey="MaTaiKhoan" Type="ChiTietDauGia" />
      <Association Name="TaiKhoan_Comment" Member="Comments" ThisKey="MaTaiKhoan" OtherKey="MaTaiKhoan" Type="Comment" />
      <Association Name="TaiKhoan_DauGiaThanhCong" Member="DauGiaThanhCongs" ThisKey="MaTaiKhoan" OtherKey="MaTaiKhoan" Type="DauGiaThanhCong" />
      <Association Name="TaiKhoan_SanPham" Member="SanPhams" ThisKey="MaTaiKhoan" OtherKey="MaTaiKhoan" Type="SanPham" />
      <Association Name="LoaiTaiKhoan_TaiKhoan" Member="LoaiTaiKhoan" ThisKey="MaLoaiTaiKhoan" OtherKey="MaLoaiTaiKhoan" Type="LoaiTaiKhoan" IsForeignKey="true" />
      <Association Name="ThongTinTaiKhoan_TaiKhoan" Member="ThongTinTaiKhoan" ThisKey="MaTaiKhoan" OtherKey="MaTaiKhoan" Type="ThongTinTaiKhoan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.THAMSO" Member="THAMSOs">
    <Type Name="THAMSO">
      <Column Name="IDThamSo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenThamSo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GiaTri" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TinhTrangSanPham" Member="TinhTrangSanPhams">
    <Type Name="TinhTrangSanPham">
      <Column Name="MaTinhTrangSanPham" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenTinhTrangSanPham" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="TinhTrangSanPham_SanPham" Member="SanPhams" ThisKey="MaTinhTrangSanPham" OtherKey="MaTinhTrangSanPham" Type="SanPham" />
    </Type>
  </Table>
</Database>