<?xml version="1.0" encoding="utf-8"?><Database Name="DauGia" Class="DataEntityDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=Wiki\SQLEXPRESS;Initial Catalog=DauGia;User ID=vbay" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DauGia" Provider="System.Data.SqlClient" />
  <Table Name="dbo.SanPham" Member="SanPhams">
    <Type Name="SanPham">
      <Column Name="MaSanPham" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenSanPham" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaLoaiSanPham" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="MaTaiKhoan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GiaKhoiDiem" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="GiaHienTai" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="NgayDang" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayHetHan" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MaTinhTrangSanPham" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MoTaSanPham" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>