//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace DK_DauGia3 {
    
    
    public partial class _Default {
        
        /// <summary>
        /// UC_TimKiemNangCao1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DK_DauGia3.UC_TimKiemNangCao UC_TimKiemNangCao1;
    }
}
